import {
  AirplaneIcon,
  BagIcon,
  BinocularsIcon,
  BonfireIcon,
  BulbIcon,
  CameraIcon,
  CapsIcon,
  Cloud,
  CloudIcon,
  CloudsIcon,
  CompassIcon,
  DogIcon,
  FireIcon,
  FlashlightIcon,
  ForestIcon,
  MapIcon,
  PawIcon,
  PetsAmenityIcon,
  PocketKnifeIcon,
  RVTrailerIcon,
  ShoesIcon,
  ShowerGreenAmenityIcon,
  ShowerIcon,
  StarIcon,
  SunglassesIcon,
  SunIcon,
  SwimmingIcon,
  TicketIcon,
  TreeIcon,
  PicnicTablesIcon,
  TrashIcon,
  WifiIcon,
  PotableWaterIcon,
  CampfireRingsIcon,
  VisitorsRecCenterIcon,
  CellServiceIcon,
  AlcoholIcon,
  CampgroundHostIcon,
  GrillsIcon,
  HikingIcon,
  FishingIcon,
  ScubaDivingIcon,
  SurfingWindsurfingIcon,
  ExhibitsGuidedToursIcon,
  SnorkelingIcon,
  SwimmingIcon2,
  BikeTrailsIcon,
  TidePoolsIcon,
  VolleyballIcon,
  CanoeingKayakingIcon,
  PhotographyIcon,
  WhaleWatchingIcon,
  BackpackingIcon,
  PlaceholderIcon,
  AdaIcon,
  RvIcon,
  PullThruIcon,
  PetIcon,
  ShowerNewIcon,
  HookupIcon,
} from './Icons'

export const iconsObjData = {
  'Picnic Tables': <PicnicTablesIcon />,
  Trash: <TrashIcon />,
  Wifi: <WifiIcon />,
  'Potable Water': <PotableWaterIcon />,
  'Campfire Rings': <CampfireRingsIcon />,
  'Visitors/Rec Center': <VisitorsRecCenterIcon />,
  'Cell Service': <CellServiceIcon />,
  Alcohol: <AlcoholIcon />,
  'Campground Host': <CampgroundHostIcon />,
  Grills: <GrillsIcon />,
  Hiking: <HikingIcon />,
  Fishing: <FishingIcon />,
  'Scuba Diving': <ScubaDivingIcon />,
  'Surfing / Windsurfing': <SurfingWindsurfingIcon />,
  'Exhibits / Guided Tours': <ExhibitsGuidedToursIcon />,
  Snorkeling: <SnorkelingIcon />,
  Swimming: <SwimmingIcon2 />,
  'Bike Trails': <BikeTrailsIcon />,
  'Tide Pools': <TidePoolsIcon />,
  Volleyball: <VolleyballIcon />,
  'Canoeing / Kayaking': <CanoeingKayakingIcon />,
  Photography: <PhotographyIcon />,
  'Whale Watching': <WhaleWatchingIcon />,
  Backpacking: <BackpackingIcon />,
  Placeholder: <PlaceholderIcon />,
  'ADA Sites': <AdaIcon />,
  'RV/Trailers': <RvIcon />,
  'Pull Through Spots': <PullThruIcon />,
  'Pet Friendly': <PetIcon />,
  Showers: <ShowerNewIcon />,
  Hookups: <HookupIcon />,
}

export const amenitiesData = [
  {
    icon: <RVTrailerIcon />,
    title: 'RV/Trailers',
    isActive: true,
  },
  {
    icon: <FlashlightIcon />,
    title: 'Hookups',
    isActive: true,
  },
  {
    icon: <CameraIcon />,
    title: 'Pull Through Spots',
    isActive: true,
  },
  {
    icon: <PetsAmenityIcon />,
    title: 'Pet Friendly',
    isActive: true,
  },
  {
    icon: <SunIcon />,
    title: 'ADA Sites',
    isActive: false,
  },
  {
    icon: <ShowerGreenAmenityIcon />,
    title: 'Showers',
    isActive: false,
  },
]
export const amenitiesSecondData = [
  {
    icon: <CapsIcon />,
    title: 'caps',
    isActive: true,
  },
  {
    icon: <CompassIcon />,
    title: 'compass',
    isActive: true,
  },
  {
    icon: <BonfireIcon />,
    title: 'bonfire',
    isActive: true,
  },
  {
    icon: <SunglassesIcon />,
    title: 'sunglasses',
    isActive: true,
  },
  {
    icon: <MapIcon />,
    title: 'map',
    isActive: true,
  },
  {
    icon: <TicketIcon />,
    title: 'ticket',
    isActive: true,
  },
  {
    icon: <AirplaneIcon />,
    title: 'airplane',
    isActive: true,
  },
  {
    icon: <BagIcon />,
    title: 'bag',
    isActive: true,
  },
  {
    icon: <ForestIcon />,
    title: 'forest',
    isActive: true,
  },
  {
    icon: <ShoesIcon />,
    title: 'shoes',
    isActive: true,
  },
  {
    icon: <CloudIcon />,
    title: 'cloud',
    isActive: true,
  },
  {
    icon: <TreeIcon />,
    title: 'tree',
    isActive: true,
  },
  {
    icon: <BinocularsIcon />,
    title: 'binoculars',
    isActive: true,
  },
  {
    icon: <PocketKnifeIcon />,
    title: 'pocket Knife',
    isActive: true,
  },
]

export const RatingSummaryData = [
  {
    star: [
      {
        starValue: <StarIcon />,
        starActive: 'star_active',
      },
      { starValue: <StarIcon />, starActive: 'star_active' },
      { starValue: <StarIcon />, starActive: 'star_active' },
      { starValue: <StarIcon />, starActive: 'star_active' },
      { starValue: <StarIcon />, starActive: ' ' },
    ],
  },
]

export const starData = [
  {
    imageUrl: <StarIcon />,
  },
  {
    imageUrl: <StarIcon />,
  },
  {
    imageUrl: <StarIcon />,
  },
  {
    imageUrl: <StarIcon />,
  },
  {
    imageUrl: <StarIcon />,
  },
]
export const heroData = {
  heading: ' Platte River Campground',
  title: ' Among Top 50 campgrounds in California',
  address: `5685 Lake Michigan Rd, Honor, MI 49640, United States`,
  contact: '+1 231 326 5134',
  email: ' www.example.com',
  star: [
    { starValue: <StarIcon />, starActive: 'star_active' },
    { starValue: <StarIcon />, starActive: 'star_active' },
    { starValue: <StarIcon />, starActive: 'star_active' },
    { starValue: <StarIcon />, starActive: 'star_active' },
    { starValue: <StarIcon />, starActive: 'star_active' },
  ],
  circleBoxText: [
    { title: '174', subtitle: 'Total Sites' },
    { title: 'All year', subtitle: 'Season' },
    { title: '45', subtitle: 'Nightly cost' },
  ],
  circleBoxIcon: [
    { icon: <DogIcon />, isActive: false },
    { icon: <ShowerIcon />, isActive: false },
    { icon: 'RV/Trailers', isActive: false },
  ],
}

export const formInputData = [
  {
    campgroundId: 120010,
    name: 'Bolsa Chica State Beach',
    maxLength: 40,
    maxPeople: 8,
    siteTypes: ['RV', 'Trailer'],
  },
  {
    campgroundId: 120015,
    name: 'Carpinteria State Beach',
    maxLength: 35,
    maxPeople: 25,
    siteTypes: ['RV', 'Trailer', 'Tent', 'Group'],
  },
  {
    campgroundId: 120025,
    name: 'Doheny State Beach',
    maxLength: 38,
    maxPeople: 8,
    siteTypes: ['RV', 'Trailer', 'Tent'],
  },
  {
    campgroundId: 120030,
    name: 'El Capitan State Beach',
    maxLength: 42,
    maxPeople: 8,
    siteTypes: ['RV', 'Trailer', 'Tent', 'Group'],
  },
  {
    campgroundId: 120047,
    name: 'Leo Carrillo State Park',
    maxLength: 31,
    maxPeople: 8,
    siteTypes: ['RV', 'Trailer', 'Tent', 'Group'],
  },
  {
    campgroundId: 120082,
    name: 'San Clemente State Beach',
    maxLength: 42,
    maxPeople: 50,
    siteTypes: ['RV', 'Trailer', 'Tent', 'Group'],
  },
  {
    campgroundId: 120083,
    name: 'San Elijo State Beach',
    maxLength: 35,
    maxPeople: 8,
    siteTypes: ['RV', 'Trailer', 'Tent'],
  },
  {
    campgroundId: 120087,
    name: 'Seacliff State Beach',
    maxLength: 40,
    maxPeople: 8,
    siteTypes: ['RV', 'Trailer'],
  },
  {
    campgroundId: 120090,
    name: 'South Carlsbad State Beach',
    maxLength: 37,
    maxPeople: 8,
    siteTypes: ['RV', 'Trailer', 'Tent'],
  },
  {
    campgroundId: 120263,
    name: 'Silver Strand State Beach',
    maxLength: 40,
    maxPeople: 8,
    siteTypes: ['RV', 'Trailer'],
  },
  {
    campgroundId: 120742,
    name: 'Crystal Cove Beach Cottages',
    maxLength: 10,
    maxPeople: 9,
    siteTypes: ['Cabin'],
  },
  {
    campgroundId: 123400,
    name: 'Crystal Cove Moro Campground',
    maxLength: 38,
    maxPeople: 8,
    siteTypes: ['RV', 'Trailer', 'Tent'],
  },
]
